############################################################
# ASCOS — Primary Application Storage (S3)
#
# SCOPE:
#   This file creates the main S3 bucket that holds ASCOS user
#   files. It is completely separate from the Terraform state
#   bucket (bootstrap/) and from any future frontend-hosting
#   bucket (Stage 9) — never reuse this bucket for those.
#
# LOGICAL TIER MAPPING (master reference §26 — decided today):
#   HOT  -> S3 Standard
#   WARM -> S3 Standard-IA
#   COLD -> S3 Glacier Instant Retrieval
#
#   Instant Retrieval was chosen over Flexible Retrieval / Deep
#   Archive specifically because it needs NO restore step (real-
#   time access), which avoids building restore/wait/poll logic
#   and multi-hour "Restoring..." UI states into tier-change-fn
#   for this project's scale (~5-10 users, one-month build).
#   Full reasoning + alternatives considered: docs/AWS_SETUP_LOG.md.
#
# IMPORTANT — WHAT THIS FILE DOES NOT DO:
#   This file does NOT implement Hot/Warm/Cold transitions. Tier
#   changes (CopyObject / RestoreObject) are performed by
#   tier-change-fn (Stage 5), driven by the ML policy engine
#   (Stage 10) or direct user action. Per master reference §27,
#   there must be exactly ONE authority for automatic tier
#   decisions — S3 lifecycle rules here are HOUSEKEEPING ONLY
#   (cleanup of incomplete uploads, old noncurrent versions) and
#   must never independently move objects between storage classes.
#
# PER-USER NAMESPACE (master reference §7):
#   Objects are stored under s3://<bucket>/{user_id}/... where
#   user_id is the Cognito `sub`. The bucket itself does not
#   enforce this — it's an object-key convention. Authorization
#   is enforced in Lambda (Stage 5/6), never assumed from the
#   prefix alone; a prefix is a namespace, not an ACL.
#
# SECURITY:
#   Private bucket, Block Public Access fully enabled, encrypted
#   at rest, versioned. No public ACLs, no public bucket policy,
#   ever. Presigned URLs (generated by Lambda, Stage 5/6) are the
#   only sanctioned way the browser ever touches this bucket.
#
# BUCKET NAMING:
#   The account ID is fetched dynamically via the
#   aws_caller_identity data source, rather than duplicating
#   bootstrap/variables.tf's state_bucket_suffix into the root
#   config. Root and bootstrap are separate Terraform
#   configurations that don't share variables — this avoids a
#   second manually-synced copy of the account ID.
############################################################

data "aws_caller_identity" "current" {}

resource "aws_s3_bucket" "app_storage" {
  bucket = "${var.project_name}-${var.environment}-storage-${data.aws_caller_identity.current.account_id}"

  tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
    Purpose     = "application-file-storage"
  }
}

# Versioning: protects against accidental overwrite/delete, and
# is a prerequisite for safe tier-transition concurrency checks
# later (master reference §17 — ETag/conditional-request guards
# against a tier job racing a user's own edit).
resource "aws_s3_bucket_versioning" "app_storage" {
  bucket = aws_s3_bucket.app_storage.id
  versioning_configuration {
    status = "Enabled"
  }
}

# Encrypt all objects at rest by default.
resource "aws_s3_bucket_server_side_encryption_configuration" "app_storage" {
  bucket = aws_s3_bucket.app_storage.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = true
  }
}

# Block Public Access — this bucket holds real user files and
# must never be publicly reachable by any mechanism (ACL, bucket
# policy, or otherwise). Master reference §28.
resource "aws_s3_bucket_public_access_block" "app_storage" {
  bucket = aws_s3_bucket.app_storage.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Deny any non-TLS access to this bucket, same pattern used for
# the Terraform state bucket in bootstrap/.
resource "aws_s3_bucket_policy" "app_storage" {
  bucket = aws_s3_bucket.app_storage.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "DenyInsecureTransport"
        Effect    = "Deny"
        Principal = "*"
        Action    = "s3:*"
        Resource = [
          aws_s3_bucket.app_storage.arn,
          "${aws_s3_bucket.app_storage.arn}/*"
        ]
        Condition = {
          Bool = {
            "aws:SecureTransport" = "false"
          }
        }
      }
    ]
  })
}

# HOUSEKEEPING-ONLY lifecycle rules. These clean up storage waste
# that has nothing to do with the ML tiering decision — they must
# NOT transition objects between storage classes. That authority
# belongs solely to tier-change-fn (Stage 5+), per master
# reference §27.
resource "aws_s3_bucket_lifecycle_configuration" "app_storage" {
  bucket = aws_s3_bucket.app_storage.id

  rule {
    id     = "abort-incomplete-multipart-uploads"
    status = "Enabled"

    filter {}

    # Large-object transitions (master reference §16) use
    # multipart copy for objects > 5GB. If one is ever left
    # incomplete (failed job, interrupted transfer), don't let
    # the orphaned parts sit around accruing storage cost forever.
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  rule {
    id     = "expire-old-noncurrent-versions"
    status = "Enabled"

    filter {}

    # Versioning (above) protects against accidental overwrite,
    # but old versions of DELETED/replaced objects shouldn't
    # accumulate forever. This is housekeeping, not tiering —
    # it removes noncurrent versions after they're old enough
    # that recovery is no longer a realistic concern, independent
    # of which logical tier the current version lives in.
    noncurrent_version_expiration {
      noncurrent_days = 90
    }
  }
}